---
galaxy_info:
  author: Homelab Admin
  description: Install and configure SNMP daemon (snmpd) for monitoring
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - monitoring
    - snmp
    - snmpd
    - network

dependencies: []
