---
galaxy_info:
  author: Homelab Admin
  description: Deploy Portainer agent container on Docker hosts
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - docker
    - portainer
    - containers
    - monitoring
    - management

dependencies: []

collections:
  - community.docker
