---
galaxy_info:
  author: Homelab Admin
  description: Automatically register Docker hosts with Portainer server via API
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - docker
    - portainer
    - containers
    - monitoring
    - management
    - api

dependencies: []
